### ISSUE TITLE
Display window size and current rows/cols on-screen

### ISSUE THREAD

**Issue by johncmerfeld** [baogorek/datascroller#10]
The user should know how big their current viewport is, as well as knowing which parts of the data frame they're currently viewing.

**Comment by baogorek** [comment]
I got started on this in [Pull Request 11](https://github.com/baogorek/datascroller/pull/11). You can see "R<rownum>" in the top left corner.

**Comment by baogorek** [comment]
Partially completed in [Pull Request 16](https://github.com/baogorek/datascroller/pull/16), as at least the top-left row and column are displayed to the user.
