### ISSUE TITLE
Scrolling a 2-column dataframe - couldn't see the second column

### ISSUE THREAD

**Issue by baogorek** [baogorek/datascroller#14]

**Comment by johncmerfeld** [comment]
Has this been resolved?

**Comment by baogorek** [comment]
Not sure. Will test later today. Can use a text file with a few dates and one other column, use dates as an index before scrolling the Pandas df. datascroller was in a different place when I logged this so it's probably resolved.

**Comment by baogorek** [comment]
Just tested with a small 2-column data set. We're good here.
