### ISSUE TITLE
Add support for various csv options

### ISSUE THREAD

**Issue by kjmerf** [baogorek/datascroller#20]
The CLI throws an error if the CSV separator is not a comma. To reproduce, save a version of the titanic file with a pipe separator:

```
import pandas as pd
df = pd.read_csv('titanic.csv')
df.to_csv('titanic_test.csv', sep='|')
```

Now run CLI on new file: 

`scroll titanic_test.csv`

A ParserError is raised. The CLI should work with multiple separators and encodings. I believe this is achievable by adding more options to the CLI that we then pass to scroller.scroll_csv.

**Comment by johncmerfeld** [comment]
Working on it. Will push soon as an optional CLI argument. I'm wondering whether there's a way to tell pandas to try with "," and if that fails to then try again with "|", "\t", etc.

Also, as per our discussion, will do the above for encoding.

**Comment by kjmerf** [comment]
You could try... except ParserError but I wouldn't go down that road
