### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from versions: none)

### ISSUE THREAD

**Issue by prerit912** [baogorek/datascroller#23]
ERROR: No matching distribution found for pkg-resources==0.0.0

Is it ok to comment out this line in the requirements.txt? It causes build to fail. [pypa/pip#4022](https://github.com/pypa/pip/issues/4022)

**Comment by baogorek** [comment]
Hey @prerit912, good call out. Sorry it took us 7 months to get back with you. `pkg-resources==0.0.0` is out of there!
