### ISSUE TITLE
help message should stay at the top

### ISSUE THREAD

**Issue by kjmerf** [baogorek/datascroller#41]
This one is likely for @johncmerfeld 

When you open datascroller, there is a really helpful message at the top that says: "Press ' (single quote) for help menu". I think this should stay visible even when you start scrolling. It disappears as soon as I scroll down. In fact, even if I scroll back up, it's not there anymore!

**Comment by johncmerfeld** [comment]
Glad to hear it. I pondered whether the behavior should be to stay at the top. I'll stick this in a PR.

**Comment by kjmerf** [comment]
This is done
