### ISSUE TITLE
Allow for queries while scrolling

### ISSUE THREAD

**Issue by baogorek** [baogorek/datascroller#9]
This is a pain in the neck way to find rows meeting some conditions:
```
all_df.loc[(all_df.date == '2019-07-15') & (all_df.x == 1) & (all_df.y == 27) & (all_df.z == 30)]
```
datascroller can add querying functionality within the live scrolling environment.

**Comment by johncmerfeld** [comment]
@baogorek some updated thoughts on this, per a discussion between myself and @kjmerf : 

### What should the control flow look like?
My thinking is that there should be one or two sentinel keys that signal a query is coming. So the user, while in the live scrolling environment, presses `'` or `"`, say. Then a blank line appears at the bottom of the screen where they can input their query, followed by `\n`. The caveat is that neither of us know exactly how to do this, but it seems like it would be straightforward.

### What should the query return?
This might sound kind of obvious, but we do need to think about how this feature (and datascroller in general) behaves for very large files. Say we implement some kind of pagination (is in #24 ), where datascroller only loads 1,000 rows at a time to keep latency down. Probably, the query result should be the first 1,000 rows of the result set from the query run against the entire dataframe. But we'll have to implement that consciously.

### Most critically, what should the query syntax be?
There's a spectrum, here. On one end is straight up SQL, which means maximum ease for the user. However, then the burden is on us to translate SQL to pandas ([although there may be a module that does this](https://pypi.org/project/pandasql/)). On the other end is that the user enters pandas syntax and we don't have to code anything. Obviously that doesn't relieve the pain point.

A middle ground could be that we create our own syntax, optimized for brevity and similarity to SQL while still being easily translatable. We document it cleanly and there's low overhead for the user. 

However, now that we've found the `pandasql` package, maybe that'll just solve this. I don't know what limitations this package has, as of now. There's a risk that it's too brittle and then it'll be harder to add functionality on our end. Curious to hear your thoughts!

**Comment by johncmerfeld** [comment]
The `pandasql` package definitely has limitations. And nobody's worked on it for a few years. Still, might suit our purposes in the short- and medium-term. And we can always use it as a jumping off point.

**Comment by baogorek** [comment]
Was just thinking about the parts of the SQL that we'd want:

* Probably minimal SELECT methodology. Filtering might come in handy. I eventually want the ability to quickly jump to a specific column.
* Joins and Unions are probably out
* Aggregation - maybe, but that could be scoped separately

So that leaves the WHERE statement, and I think that's the place we'll get the most bang for our buck. If we could make something similar to dplyr's filter (user doesn't have to retype the data frame before each column) while in the datascroller view, I think it'd be a pleasure to use. (As a vim user I'd love to press "/" to get into search mode, but that could be configurable).

Glad that the data chunking is in the conversation now. I could see our WHERE functionality looping through all data chunks sequentially. That also makes datascroller a tool that can handle data too big to fit in memory, which is a cool distinction!

**Comment by johncmerfeld** [comment]
@baogorek Exciting update on this!

Check out my `querying` branch. I've got your Vim-like line search working, just press `;` and enter the line number you want. If it's out past the edge of the dataframe, it'll just jump to the bottom or the top, depending on which direction it's out of bounds.

Per our discussion yesterday, I have some infrastructure in place for the user to input pandas code. Implementing this will take a little more thought, though, since it will actually affect properties of the underlying dataframe. Do we modify the object the DFWindow class is working with, but save a copy of the original dataframe?

**Comment by johncmerfeld** [comment]
The more I think about this, the more I'm intrigued by the idea of creating our own query language. Frankly I find it way too cumbersome to do basic filtering in both Pandas and dplyr-like syntax. I mean, how complicated are people going to be getting while scrolling? Surely we just need a way to handle WHERE conditions, like you said above. SELECT should be easy enough.
